checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: /fsx/phuc/new_workspace/experiments/fp8_for_nanotron/exp672e1_7b_bfloat16_mixed_like_exp669d1_and_elie_data_and_tp4_and_dp1_and_pp_2_and_mbs16_and_accump_20_and_gbs_300k_and_80k_steps_and_20b_tokens_and_gclip1.0_lr_3.0e-4_and_warmup_1000_but_aeps1.0e-6/checkpoints/
  # checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  # resume_checkpoint_path: /fsx/phuc/new_workspace/experiments/fp8_for_nanotron/exp608ba1_100m_fp8_like_exp602ah01_with_fp8_optim_and_adam_epsilon_1.0e-5_and_smol_ds_but_tp8_and_dp10_and_mbs_2560_and_gbs_1.6m_and_100b_tokens_and_70k_steps.6m_and_100b_tokens_and_70k_steps/checkpoints/
  save_initial_state: false

# NOTE: the old one
# data_stages:
# - data:
#     dataset:
#       dataset_overwrite_cache: false
#       dataset_processing_num_proc_per_process: 1
#       hf_dataset_config_name: null
#       hf_dataset_or_datasets: roneneldan/TinyStories
#       hf_dataset_splits: train
#       text_column_name: text
#     num_loading_workers: 1
#     seed: 42
#   name: Stable Training Stage
#   start_training_step: 1

# data:
#   dataset:
#     dataloader_type: single
#     dataset_max_tokens: null
#     dataset_weights:
#     - 0.5
#     - 0.4
#     - 0.1
#     datasets:
#     - filename_pattern: .*.ds
#       folder: /fsx/loubna/tokenized_for_exps/fw_edu/fineweb-edu-full-cosmo2_merged
#       skip_tokens: 0
#     - filename_pattern: .*.ds
#       folder: /fsx/loubna/tokenized_for_exps/fw_edu/dclm-3T-cosmo2_merged
#       skip_tokens: 0
#     - filename_pattern: .*.ds
#       folder: /fsx/loubna/tokenized_for_exps/fw_edu/starcoderdata-full-cosmo_merged
#       skip_tokens: 0
#     pad_samples_to_global_batch_size: false
#     skip_in_stream: true
#   num_loading_workers: 0
#   seed: 42

data_stages:
- data:
    dataset:
      dataloader_type: single
      dataset_max_tokens: null
      dataset_weights:
      - 0.5
      - 0.4
      - 0.1
      datasets:
      - filename_pattern: .*.ds
        # folder: /fsx/loubna/tokenized_for_exps/fw_edu/fineweb-edu-full-cosmo2_merged
        folder: /fsx/elie_bakouch/data/smollmv1
        skip_tokens: 0
      - filename_pattern: .*.ds
        # NOTE: lobuna deleted it
        # folder: /fsx/loubna/tokenized_for_exps/fw_edu/dclm-3T-cosmo2_merged
        folder: /fsx/phuc/datasets/100b_smol_ds/fw_edu_dclm_subset
        skip_tokens: 0
      - filename_pattern: .*.ds
        folder: /fsx/loubna/tokenized_for_exps/fw_edu/starcoderdata-full-cosmo_merged
        skip_tokens: 0
      pad_samples_to_global_batch_size: false
      skip_in_stream: true
    num_loading_workers: 0
    seed: 42
  name: Stable Training Stage
  start_training_step: 1

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: fp8_for_nanotron
  run: exp672e1_7b_bfloat16_mixed_like_exp669d1_and_elie_data_and_tp4_and_dp1_and_pp_2_and_mbs16_and_accump_20_and_gbs_300k_and_80k_steps_and_20b_tokens_and_gclip1.0_lr_3.0e-4_and_warmup_1000_but_aeps1.0e-6
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
  # monitor_model_states: false
  # monitor_model_states_using_hooks: false
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    # std: 0.25 # sqrt(1/16)
    # std: 0.125 # sqrt(1/64)
    # std: 0.04419417382415922 # sqrt(1/512)
    # std: 0.02209708691207961 # sqrt(1/2048)
    std: 0.015625 # sqrt(1/4096)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02

    hidden_size: 4096
    intermediate_size: 16384
    num_hidden_layers: 26

    is_llama_config: true
    max_position_embeddings: 1024
    num_attention_heads: 16
    num_key_value_heads: 16
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152

optimizer:
  accumulate_grad_in_fp32: true
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 1000 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 0.00003

  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-06
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 0
  clip_grad: 1.0
  # update_clipping: true

parallelism:
  # large batch training
  dp: 1
  tp: 4
  # dp: 2
  # tp: 2
  expert_parallel_size: 1
  pp: 2
  pp_engine: 1f1b
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  # NOTE: micro_batch_size * sequence_length * batch_accumulation_per_replica
  # = 128 * 256 * 1 = 16384
  batch_accumulation_per_replica: 20
  limit_test_batches: 0
  limit_val_batches: 0
  # large batch training
  micro_batch_size: 16 # 16 * 1024 * 8 = 130k tokens per batch
  # micro_batch_size: 16
  sequence_length: 1024
  train_steps: 80_000
  val_check_interval: -1

s3_upload:
  remove_after_upload: true
  s5cmd_concurrency: 5
  s5cmd_numworkers: 16
  s5cmd_path: /fsx/nouamane/miniconda/envs/2-1-cu121/bin/s5cmd
  upload_s3_path: s3://phuc-experiments/fp8_for_nanotron/exp672e1_7b_bfloat16_mixed_like_exp669d1_and_elie_data_and_tp4_and_dp1_and_pp_2_and_mbs16_and_accump_20_and_gbs_300k_and_80k_steps_and_20b_tokens_and_gclip1.0_lr_3.0e-4_and_warmup_1000_but_aeps1.0e-6

experiment_logger:
  # id: exp614ba4_100m_fp8_like_exp602ah01_with_fp8_optim_and_adam_epsilon_1.0e-7_and_smol_ds_but_tp8_and_dp10_and_mbs_2560_and_gbs_1.6m_and_100b_tokens_and_70k_steps
  tensorboard_logger:
    flush_secs: 30
    tensorboard_dir: /fsx/phuc/new_workspace/experiments/fp8_for_nanotron/exp672e1_7b_bfloat16_mixed_like_exp669d1_and_elie_data_and_tp4_and_dp1_and_pp_2_and_mbs16_and_accump_20_and_gbs_300k_and_80k_steps_and_20b_tokens_and_gclip1.0_lr_3.0e-4_and_warmup_1000_but_aeps1.0e-6/logs/tb_logs
  wandb_logger:
    wandb_entity: neuralink
    wandb_project: fp8_for_nanotron
